#!/bin/bash

wsicapstatus=`sv status wsicapd |cut -d ' ' -f 1`
squidstatus=`sv status squid |cut -d ' ' -f 1`

if [[ "$wsicapstatus" != "run:" ]]
then exit 1
fi
if [[ "$squidstatus" != "run:" ]]
then exit 1
fi

source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND

