#!/bin/bash

qlpstatus=`sv status qlproxy |cut -d ' ' -f 1`
wsmgrstatus=`sv status wsmgr |cut -d ' ' -f 1`
squidstatus=`sv status squid |cut -d ' ' -f 1`

if [[ "$qlpstatus" != "run:" ]]
then exit 1
fi
if [[ "$wsmgrstatus" != "run:" ]]
then exit 1
fi
if [[ "$squidstatus" != "run:" ]]
then exit 1
fi

/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"

