#!/bin/bash

# let qlproxy and wsmgr start before squid - exit script until they're running
qlpstatus=`sv status qlproxy |cut -d ' ' -f 1`
wsmgrstatus=`sv status wsmgr |cut -d ' ' -f 1`

if [[ "$qlpstatus" != "run:" ]]
then exit 1
fi
if [[ "$wsmgrstatus" != "run:" ]]
then exit 1
fi

SQUID_NAME=squid3
SQUID_PATH=/usr/sbin/$SQUID_NAME
SQUID_CONF=/etc/squid3/squid.conf

ulimit -n 65535 
exec $SQUID_PATH -N -YC -f $SQUID_CONF 
