#!/bin/bash

SQUID_NAME=squid
SQUID_PATH=/usr/sbin/$SQUID_NAME
SQUID_CONF=/etc/squid/squid.conf
MAX_ATTEMPTS=5

$SQUID_PATH -k shutdown

attempt=1

until [[ "$attempt" -gt "$MAX_ATTEMPTS" ]]
do
    printf "Waiting for qlproxy."
    pid=$(pidof qlproxyd)

    if [[ "$pid" -ne "" ]]; then
        break
    fi
    ((attempt++))

    sleep 1 
    printf "."
done
printf "\n"
 
if [[ "$attempt" -lt "$MAX_ATTEMPTS" ]]; then 
    echo "Initializing squid..." 
    $SQUID_PATH -z -YC -f $SQUID_CONF 
    echo "Squid initialized" 
 
    echo "Starting squid" 
    ulimit -n 65535 
    $SQUID_PATH -N -YC -f $SQUID_CONF 
    echo "Squid started" 
else 
    echo "Neither qlproxy nor squid was started" 
    exit 1 
fi 
